# Visit: https://github.com/the-teacher/rails-start

# =-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=
# Rails Start - Fast Track to Rails Development
# =-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=
# Visit: https://github.com/the-teacher/rails-start
#
# Rails Start helps companies, entrepreneurs, and Rails learners get started quickly.
# Created by Ilya Zykin (https://github.com/the-teacher)
#
# ⭐ Support the project - leave your stars on GitHub and tell your colleagues!
# =-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=

include Makefiles/100_Base-Images.mk
include Makefiles/200_Main-Images.mk
include Makefiles/300_Media-Images.mk
include Makefiles/1000_Common-Images.mk

# Main help command
help:
	@echo "Rails Start - Commands to prepare Images"
	@echo "=============================================================="
	@echo "Detailed help by category:"
	@echo "  make base-images-help    - Base image building commands"
	@echo "  make main-images-help    - Main image building commands"
	@echo "  make common-images-help  - General images commands"
	@echo "  make media-images-help   - Media images commands"
	@echo "=============================================================="