include Makefiles/100_Base-Images.mk
include Makefiles/200_Main-Images.mk
include Makefiles/300_Media-Images.mk
include Makefiles/1000_Common-Images.mk

# Main help command
help:
	@echo "Rails Start - Commands to prepare Images"
	@echo "=============================================================="
	@echo "Detailed help by category:"
	@echo "  make base-images-help    - Base image building commands"
	@echo "  make main-images-help    - Main image building commands"
	@echo "  make common-images-help  - General images commands"
	@echo "  make media-images-help   - Media images commands"
	@echo "=============================================================="