default: &default
  pool: 5
  adapter:  postgresql
  encoding: unicode

test:
  <<: *default
  host: <%=ENV['DATABASE_HOSTNAME']%>
  username: <%=ENV['DATABASE_USERNAME']%>
  password: <%=ENV['DATABASE_PASSWORD']%>
  database: rails7app_test
  

development:
  <<: *default
  host: <%=ENV['DATABASE_HOSTNAME']%>
  username: <%=ENV['DATABASE_USERNAME']%>
  password: <%=ENV['DATABASE_PASSWORD']%>
  database: rails7app_development

production:
  <<: *default
  url: <%= ENV['DATABASE_PRODUCTION'] %>
